# Override the default values of the info endpoint
info:
    app:
        name: ${name}
        description: ${description}
        version: ${version}
        realm: development

# enable shutdown of application via a POST
endpoints:
    shutdown:
        enabled: true
    health:
        sensitive: false    # display full details for non-authenticated requests

# show the banner file during startup
spring:
    main:
        show_banner: true

    data:
        mongodb:
            host: mongodb
            port: 27017
#           authenticationDatabase: admin
#           username: readWrite
#           password: readWrite
            database: monitor
            repositories:
                enabled: true

    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true

# specify the port the service should bind to when using the embedded container, a value of 0 will bind to a randomly selected available port
server:
    port: 8100

# be ready for HTTP proxying
    tomcat:
        remote_ip_header: x-forwarded-for
        protocol_header: x-forwarded-proto

security:
    basic:
        enabled: false

# the context to use for the operation actuators, eg /operations/info
management:
    context-path: /operations
    security:
        enabled: false

# operations shell
shell:
    auth:
        simple:
            user:
                name: operations
                password: operations

# which logback configuration file to use
logging:
    config: classpath:logback.xml

example:
    exchange: monitoring
    requireCorrelationId: true

#---------e Profile specific overrides ----------#

# integration testing
---
spring:
    profiles: integration

info:
    app:
        realm: integration-test

# live
---
spring:
    profiles: live

info:
    app:
        realm: production
